version: '3.7'
services:
  php:
    build:
      context: ./docker/php
      args:
        - PUID=1000
        - LIVE=
    expose:
      - '9000'
      - '9001'
    volumes:
      - .:/var/www/app:cached
    networks:
      - application


networks:
  application:
    driver: bridge
